-- =============================================
-- ElectroHuila - Initial Database Setup
-- Script para crear el esquema y tablas iniciales
-- =============================================

-- =============================================
-- 1. Crear usuario/schema ADMIN (si no existe)
-- Ejecutar como DBA
-- =============================================
-- CREATE USER ADMIN IDENTIFIED BY "YourSecurePassword123!";
-- GRANT CONNECT, RESOURCE TO ADMIN;
-- GRANT CREATE SESSION TO ADMIN;
-- GRANT CREATE TABLE TO ADMIN;
-- GRANT CREATE SEQUENCE TO ADMIN;
-- GRANT UNLIMITED TABLESPACE TO ADMIN;

-- =============================================
-- 2. Conectarse como ADMIN
-- =============================================

-- =============================================
-- 3. Crear Secuencias
-- =============================================
CREATE SEQUENCE ADMIN.SEQ_BRANCHES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADMIN.SEQ_CLIENTS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADMIN.SEQ_APPOINTMENTS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADMIN.SEQ_APPOINTMENT_TYPES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADMIN.SEQ_AVAILABLE_TIMES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADMIN.SEQ_NEW_ACCOUNTS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADMIN.SEQ_PROJECT_NEWS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADMIN.SEQ_USERS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADMIN.SEQ_ROLES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADMIN.SEQ_PERMISSIONS START WITH 1 INCREMENT BY 1;

-- =============================================
-- 4. Crear Tablas
-- =============================================

-- BRANCHES (Sucursales)
CREATE TABLE ADMIN.BRANCHES (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CODE VARCHAR2(20) NOT NULL UNIQUE,
    ADDRESS VARCHAR2(200) NOT NULL,
    PHONE VARCHAR2(20),
    CITY VARCHAR2(100) NOT NULL,
    STATE VARCHAR2(100) NOT NULL,
    IS_MAIN NUMBER(1) DEFAULT 0,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CREATED_BY NUMBER,
    UPDATED_BY NUMBER,
    DELETED_AT TIMESTAMP,
    DELETED_BY NUMBER
);

-- CLIENTS (Clientes)
CREATE TABLE ADMIN.CLIENTS (
    ID NUMBER PRIMARY KEY,
    DOCUMENT_NUMBER VARCHAR2(20) NOT NULL UNIQUE,
    DOCUMENT_TYPE VARCHAR2(10) NOT NULL,
    FULL_NAME VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(200),
    CITY VARCHAR2(100),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CREATED_BY NUMBER,
    UPDATED_BY NUMBER,
    DELETED_AT TIMESTAMP,
    DELETED_BY NUMBER
);

-- APPOINTMENT_TYPES (Tipos de Cita)
CREATE TABLE ADMIN.APPOINTMENT_TYPES (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    DURATION_MINUTES NUMBER NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CREATED_BY NUMBER,
    UPDATED_BY NUMBER,
    DELETED_AT TIMESTAMP,
    DELETED_BY NUMBER
);

-- AVAILABLE_TIMES (Horarios Disponibles)
CREATE TABLE ADMIN.AVAILABLE_TIMES (
    ID NUMBER PRIMARY KEY,
    BRANCH_ID NUMBER NOT NULL,
    APPOINTMENT_TYPE_ID NUMBER NOT NULL,
    DAY_OF_WEEK NUMBER NOT NULL, -- 0=Domingo, 1=Lunes, ..., 6=Sábado
    START_TIME VARCHAR2(10) NOT NULL,
    END_TIME VARCHAR2(10) NOT NULL,
    MAX_APPOINTMENTS NUMBER DEFAULT 5,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CREATED_BY NUMBER,
    UPDATED_BY NUMBER,
    CONSTRAINT FK_AVAIL_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES ADMIN.BRANCHES(ID),
    CONSTRAINT FK_AVAIL_APT_TYPE FOREIGN KEY (APPOINTMENT_TYPE_ID) REFERENCES ADMIN.APPOINTMENT_TYPES(ID)
);

-- APPOINTMENTS (Citas)
CREATE TABLE ADMIN.APPOINTMENTS (
    ID NUMBER PRIMARY KEY,
    APPOINTMENT_NUMBER VARCHAR2(50) NOT NULL UNIQUE,
    CLIENT_ID NUMBER NOT NULL,
    BRANCH_ID NUMBER NOT NULL,
    APPOINTMENT_TYPE_ID NUMBER NOT NULL,
    APPOINTMENT_DATE TIMESTAMP NOT NULL,
    APPOINTMENT_TIME VARCHAR2(20) NOT NULL,
    STATUS NUMBER NOT NULL, -- 0=Pending, 1=Confirmed, 2=Completed, 3=Cancelled, 4=Missed
    NOTES VARCHAR2(1000),
    CANCELLATION_REASON VARCHAR2(500),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CREATED_BY NUMBER,
    UPDATED_BY NUMBER,
    DELETED_AT TIMESTAMP,
    DELETED_BY NUMBER,
    CONSTRAINT FK_APT_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES ADMIN.CLIENTS(ID),
    CONSTRAINT FK_APT_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES ADMIN.BRANCHES(ID),
    CONSTRAINT FK_APT_TYPE FOREIGN KEY (APPOINTMENT_TYPE_ID) REFERENCES ADMIN.APPOINTMENT_TYPES(ID)
);

-- NEW_ACCOUNTS (Nuevas Acometidas)
CREATE TABLE ADMIN.NEW_ACCOUNTS (
    ID NUMBER PRIMARY KEY,
    REQUEST_NUMBER VARCHAR2(50) NOT NULL UNIQUE,
    CLIENT_ID NUMBER NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL,
    CITY VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(50) NOT NULL,
    REQUEST_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    COMPLETION_DATE TIMESTAMP,
    NOTES VARCHAR2(1000),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CREATED_BY NUMBER,
    UPDATED_BY NUMBER,
    DELETED_AT TIMESTAMP,
    DELETED_BY NUMBER,
    CONSTRAINT FK_NEW_ACC_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES ADMIN.CLIENTS(ID)
);

-- PROJECT_NEWS (Proyectos Nuevos)
CREATE TABLE ADMIN.PROJECT_NEWS (
    ID NUMBER PRIMARY KEY,
    PROJECT_NUMBER VARCHAR2(50) NOT NULL UNIQUE,
    CLIENT_DOCUMENT VARCHAR2(20) NOT NULL,
    CLIENT_NAME VARCHAR2(200) NOT NULL,
    PROJECT_TYPE VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    STATUS VARCHAR2(50) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CREATED_BY NUMBER,
    UPDATED_BY NUMBER,
    DELETED_AT TIMESTAMP,
    DELETED_BY NUMBER
);

-- USERS (Usuarios del sistema)
CREATE TABLE ADMIN.USERS (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(500) NOT NULL,
    FULL_NAME VARCHAR2(200) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CREATED_BY NUMBER,
    UPDATED_BY NUMBER,
    DELETED_AT TIMESTAMP,
    DELETED_BY NUMBER
);

-- ROLES (Roles del sistema)
CREATE TABLE ADMIN.ROLES (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CODE VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(500),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CREATED_BY NUMBER,
    UPDATED_BY NUMBER,
    DELETED_AT TIMESTAMP,
    DELETED_BY NUMBER
);

-- USER_ROLES (Relación Usuarios-Roles)
CREATE TABLE ADMIN.USER_ROLES (
    USER_ID NUMBER NOT NULL,
    ROL_ID NUMBER NOT NULL,
    PRIMARY KEY (USER_ID, ROL_ID),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES ADMIN.USERS(ID),
    CONSTRAINT FK_USER_ROLES_ROL FOREIGN KEY (ROL_ID) REFERENCES ADMIN.ROLES(ID)
);

-- PERMISSIONS (Permisos)
CREATE TABLE ADMIN.PERMISSIONS (
    ID NUMBER PRIMARY KEY,
    MODULE VARCHAR2(100) NOT NULL,
    ACTION VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP
);

-- ROL_PERMISSIONS (Permisos por Rol)
CREATE TABLE ADMIN.ROL_PERMISSIONS (
    ROL_ID NUMBER NOT NULL,
    PERMISSION_ID NUMBER NOT NULL,
    PRIMARY KEY (ROL_ID, PERMISSION_ID),
    CONSTRAINT FK_ROL_PERM_ROL FOREIGN KEY (ROL_ID) REFERENCES ADMIN.ROLES(ID),
    CONSTRAINT FK_ROL_PERM_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES ADMIN.PERMISSIONS(ID)
);

-- =============================================
-- 5. Crear Índices
-- =============================================
CREATE INDEX IDX_APPOINTMENTS_CLIENT ON ADMIN.APPOINTMENTS(CLIENT_ID);
CREATE INDEX IDX_APPOINTMENTS_BRANCH ON ADMIN.APPOINTMENTS(BRANCH_ID);
CREATE INDEX IDX_APPOINTMENTS_DATE ON ADMIN.APPOINTMENTS(APPOINTMENT_DATE);
CREATE INDEX IDX_APPOINTMENTS_STATUS ON ADMIN.APPOINTMENTS(STATUS);
CREATE INDEX IDX_CLIENTS_DOCUMENT ON ADMIN.CLIENTS(DOCUMENT_NUMBER);
CREATE INDEX IDX_USERS_USERNAME ON ADMIN.USERS(USERNAME);
CREATE INDEX IDX_USERS_EMAIL ON ADMIN.USERS(EMAIL);

-- =============================================
-- 6. Comentarios en Tablas
-- =============================================
COMMENT ON TABLE ADMIN.BRANCHES IS 'Sucursales de ElectroHuila';
COMMENT ON TABLE ADMIN.CLIENTS IS 'Clientes del sistema';
COMMENT ON TABLE ADMIN.APPOINTMENTS IS 'Citas agendadas';
COMMENT ON TABLE ADMIN.APPOINTMENT_TYPES IS 'Tipos de cita disponibles';
COMMENT ON TABLE ADMIN.USERS IS 'Usuarios del sistema';
COMMENT ON TABLE ADMIN.ROLES IS 'Roles de seguridad';

-- =============================================
-- 7. Verificación
-- =============================================
SELECT 'Database setup completado correctamente' AS STATUS FROM DUAL;
SELECT COUNT(*) AS TOTAL_TABLES FROM USER_TABLES WHERE TABLESPACE_NAME IS NOT NULL;

COMMIT;