-- =============================================
-- ElectroHuila - Theme Settings Table
-- Script para crear la tabla de configuración de temas
-- =============================================

-- Crear secuencia para THEME_SETTINGS
CREATE SEQUENCE ADMIN.SEQ_THEME_SETTINGS START WITH 1 INCREMENT BY 1;

-- Crear tabla THEME_SETTINGS
CREATE TABLE ADMIN.THEME_SETTINGS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),

    -- Colores principales
    COLOR_PRIMARY VARCHAR2(7) DEFAULT '#203461' NOT NULL,
    COLOR_SECONDARY VARCHAR2(7) DEFAULT '#1797D5' NOT NULL,
    COLOR_ACCENT VARCHAR2(7) DEFAULT '#56C2E1' NOT NULL,
    COLOR_INTERMEDIATE VARCHAR2(7) DEFAULT '#1A6192' NOT NULL,

    -- Colores de estado
    COLOR_SUCCESS VARCHAR2(7) DEFAULT '#22C55E' NOT NULL,
    COLOR_ERROR VARCHAR2(7) DEFAULT '#EF4444' NOT NULL,
    COLOR_WARNING VARCHAR2(7) DEFAULT '#F59E0B' NOT NULL,
    COLOR_INFO VARCHAR2(7) DEFAULT '#3B82F6' NOT NULL,

    -- Colores de fondo y texto
    BACKGROUND_PRIMARY VARCHAR2(7) DEFAULT '#FFFFFF' NOT NULL,
    BACKGROUND_SECONDARY VARCHAR2(7) DEFAULT '#F9FAFB' NOT NULL,
    TEXT_PRIMARY VARCHAR2(7) DEFAULT '#111827' NOT NULL,
    TEXT_SECONDARY VARCHAR2(7) DEFAULT '#6B7280' NOT NULL,

    -- Configuración de scrollbar
    SCROLLBAR_GRADIENT_START VARCHAR2(7) DEFAULT '#1797D5' NOT NULL,
    SCROLLBAR_GRADIENT_END VARCHAR2(7) DEFAULT '#56C2E1' NOT NULL,
    SCROLLBAR_HOVER_START VARCHAR2(7) DEFAULT '#203461' NOT NULL,
    SCROLLBAR_HOVER_END VARCHAR2(7) DEFAULT '#1797D5' NOT NULL,

    -- Flags
    IS_DEFAULT_THEME NUMBER(1) DEFAULT 0,
    IS_ACTIVE NUMBER(1) DEFAULT 1,

    -- Auditoría
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Crear trigger para actualizar UPDATED_AT
CREATE OR REPLACE TRIGGER ADMIN.TRG_THEME_SETTINGS_UPDATE
BEFORE UPDATE ON ADMIN.THEME_SETTINGS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Insertar tema por defecto
INSERT INTO ADMIN.THEME_SETTINGS (
    ID,
    NAME,
    DESCRIPTION,
    COLOR_PRIMARY,
    COLOR_SECONDARY,
    COLOR_ACCENT,
    COLOR_INTERMEDIATE,
    COLOR_SUCCESS,
    COLOR_ERROR,
    COLOR_WARNING,
    COLOR_INFO,
    BACKGROUND_PRIMARY,
    BACKGROUND_SECONDARY,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
    SCROLLBAR_GRADIENT_START,
    SCROLLBAR_GRADIENT_END,
    SCROLLBAR_HOVER_START,
    SCROLLBAR_HOVER_END,
    IS_DEFAULT_THEME,
    IS_ACTIVE
) VALUES (
    ADMIN.SEQ_THEME_SETTINGS.NEXTVAL,
    'ElectroHuila Default',
    'Tema por defecto de ElectroHuila',
    '#203461',  -- COLOR_PRIMARY
    '#1797D5',  -- COLOR_SECONDARY
    '#56C2E1',  -- COLOR_ACCENT
    '#1A6192',  -- COLOR_INTERMEDIATE
    '#22C55E',  -- COLOR_SUCCESS
    '#EF4444',  -- COLOR_ERROR
    '#F59E0B',  -- COLOR_WARNING
    '#3B82F6',  -- COLOR_INFO
    '#FFFFFF',  -- BACKGROUND_PRIMARY
    '#F9FAFB',  -- BACKGROUND_SECONDARY
    '#111827',  -- TEXT_PRIMARY
    '#6B7280',  -- TEXT_SECONDARY
    '#1797D5',  -- SCROLLBAR_GRADIENT_START
    '#56C2E1',  -- SCROLLBAR_GRADIENT_END
    '#203461',  -- SCROLLBAR_HOVER_START
    '#1797D5',  -- SCROLLBAR_HOVER_END
    1,          -- IS_DEFAULT_THEME
    1           -- IS_ACTIVE
);

COMMIT;

-- Verificar que se insertó correctamente
SELECT * FROM ADMIN.THEME_SETTINGS;
