-- =====================================================================
-- SCRIPT DE RESET COMPLETO - ALINEADO CON BACKEND .NET
-- =====================================================================
-- VERSION: 4.0 - Limpieza de tablas eliminadas y migración a Enums
-- Cambios desde v3.0:
--   - DocumentType ahora es ENUM en código C# (no tabla)
--   - Clients.DOCUMENT_TYPE es NUMBER para almacenar enum (1=CC, 2=TI, 3=RC, 4=CE)
--   - ELIMINADAS: DocumentTypes, NewAccounts, ProjectNews, NewAccountStatuses
--   - Sistema unificado de citas (Appointments) para todos los flujos
--   - Todas las tablas y columnas coinciden con EntityTypeConfiguration
-- =====================================================================

SET SERVEROUTPUT ON;

PROMPT ===============================================
PROMPT    RESET DE BASE DE DATOS (ALINEADO CON .NET)
PROMPT ===============================================

-- ===================== DROP ALL TABLES =====================
DECLARE
    sql_stmt VARCHAR2(1000);
BEGIN
    -- Eliminar tablas del esquema ADMIN
    FOR c IN (SELECT table_name FROM all_tables WHERE owner = 'ADMIN' AND table_name NOT LIKE 'BIN$%') LOOP
        BEGIN
            sql_stmt := 'DROP TABLE ADMIN.' || c.table_name || ' CASCADE CONSTRAINTS PURGE';
            EXECUTE IMMEDIATE sql_stmt;
            DBMS_OUTPUT.PUT_LINE('Table dropped from ADMIN: ' || c.table_name);
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Could not drop ADMIN.' || c.table_name || ': ' || SQLERRM);
        END;
    END LOOP;

    -- Eliminar tablas del esquema actual
    FOR c IN (SELECT table_name FROM user_tables WHERE table_name NOT LIKE 'BIN$%') LOOP
        BEGIN
            sql_stmt := 'DROP TABLE ' || c.table_name || ' CASCADE CONSTRAINTS PURGE';
            EXECUTE IMMEDIATE sql_stmt;
            DBMS_OUTPUT.PUT_LINE('Table dropped from current schema: ' || c.table_name);
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Could not drop ' || c.table_name || ': ' || SQLERRM);
        END;
    END LOOP;
END;
/

-- ===================== DROP ALL SEQUENCES =====================
DECLARE
    sql_stmt VARCHAR2(1000);
BEGIN
    -- Eliminar secuencias del esquema ADMIN
    FOR c IN (SELECT sequence_name FROM all_sequences WHERE sequence_owner = 'ADMIN') LOOP
        BEGIN
            sql_stmt := 'DROP SEQUENCE ADMIN.' || c.sequence_name;
            EXECUTE IMMEDIATE sql_stmt;
            DBMS_OUTPUT.PUT_LINE('Sequence dropped from ADMIN: ' || c.sequence_name);
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Could not drop ADMIN.' || c.sequence_name || ': ' || SQLERRM);
        END;
    END LOOP;

    -- Eliminar secuencias del esquema actual
    FOR c IN (SELECT sequence_name FROM user_sequences) LOOP
        BEGIN
            sql_stmt := 'DROP SEQUENCE ' || c.sequence_name;
            EXECUTE IMMEDIATE sql_stmt;
            DBMS_OUTPUT.PUT_LINE('Sequence dropped from current schema: ' || c.sequence_name);
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Could not drop ' || c.sequence_name || ': ' || SQLERRM);
        END;
    END LOOP;
END;
/

-- ===================== DROP ALL TRIGGERS =====================
DECLARE
    sql_stmt VARCHAR2(1000);
BEGIN
    -- Eliminar triggers del esquema ADMIN
    FOR c IN (SELECT trigger_name FROM all_triggers WHERE owner = 'ADMIN' AND trigger_name NOT LIKE 'BIN$%') LOOP
        BEGIN
            sql_stmt := 'DROP TRIGGER ADMIN.' || c.trigger_name;
            EXECUTE IMMEDIATE sql_stmt;
            DBMS_OUTPUT.PUT_LINE('Trigger dropped from ADMIN: ' || c.trigger_name);
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Could not drop ADMIN.' || c.trigger_name || ': ' || SQLERRM);
        END;
    END LOOP;

    -- Eliminar triggers del esquema actual
    FOR c IN (SELECT trigger_name FROM user_triggers WHERE trigger_name NOT LIKE 'BIN$%') LOOP
        BEGIN
            sql_stmt := 'DROP TRIGGER ' || c.trigger_name;
            EXECUTE IMMEDIATE sql_stmt;
            DBMS_OUTPUT.PUT_LINE('Trigger dropped from current schema: ' || c.trigger_name);
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Could not drop ' || c.trigger_name || ': ' || SQLERRM);
        END;
    END LOOP;
END;
/

-- ===================== CREATE CATALOG TABLES =====================

PROMPT 📋 Creando Tablas de Catálogo...

-- APPOINTMENT STATUS
CREATE TABLE ADMIN.AppointmentStatuses (
    ID NUMBER PRIMARY KEY,
    CODE NVARCHAR2(50) NOT NULL UNIQUE,
    NAME NVARCHAR2(100) NOT NULL,
    DESCRIPTION NVARCHAR2(500),
    COLOR_PRIMARY NVARCHAR2(20),
    COLOR_SECONDARY NVARCHAR2(20),
    COLOR_TEXT NVARCHAR2(20),
    ICON_NAME NVARCHAR2(100),
    DISPLAY_ORDER NUMBER DEFAULT 0,
    ALLOW_CANCELLATION NUMBER(1) DEFAULT 1,
    IS_FINAL_STATE NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Sequence for AppointmentStatuses
CREATE SEQUENCE ADMIN.SEQ_APPOINTMENT_STATUSES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for AppointmentStatuses
CREATE OR REPLACE TRIGGER ADMIN.TRG_APPOINTMENT_STATUSES_BI
BEFORE INSERT ON ADMIN.AppointmentStatuses
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_APPOINTMENT_STATUSES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- PROJECT TYPES
CREATE TABLE ADMIN.ProjectTypes (
    ID NUMBER PRIMARY KEY,
    CODE NVARCHAR2(50) NOT NULL UNIQUE,
    NAME NVARCHAR2(100) NOT NULL,
    DESCRIPTION NVARCHAR2(500),
    ICON_NAME NVARCHAR2(100),
    COLOR_PRIMARY NVARCHAR2(20),
    DISPLAY_ORDER NUMBER DEFAULT 0,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Sequence for ProjectTypes
CREATE SEQUENCE ADMIN.SEQ_PROJECT_TYPES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for ProjectTypes
CREATE OR REPLACE TRIGGER ADMIN.TRG_PROJECT_TYPES_BI
BEFORE INSERT ON ADMIN.ProjectTypes
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_PROJECT_TYPES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- PROPERTY TYPES
CREATE TABLE ADMIN.PropertyTypes (
    ID NUMBER PRIMARY KEY,
    CODE NVARCHAR2(50) NOT NULL UNIQUE,
    NAME NVARCHAR2(100) NOT NULL,
    ICON_NAME NVARCHAR2(100),
    DISPLAY_ORDER NUMBER DEFAULT 0,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Sequence for PropertyTypes
CREATE SEQUENCE ADMIN.SEQ_PROPERTY_TYPES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for PropertyTypes
CREATE OR REPLACE TRIGGER ADMIN.TRG_PROPERTY_TYPES_BI
BEFORE INSERT ON ADMIN.PropertyTypes
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_PROPERTY_TYPES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- SERVICE USE TYPES
CREATE TABLE ADMIN.ServiceUseTypes (
    ID NUMBER PRIMARY KEY,
    CODE NVARCHAR2(50) NOT NULL UNIQUE,
    NAME NVARCHAR2(100) NOT NULL,
    DISPLAY_ORDER NUMBER DEFAULT 0,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Sequence for ServiceUseTypes
CREATE SEQUENCE ADMIN.SEQ_SERVICE_USE_TYPES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for ServiceUseTypes
CREATE OR REPLACE TRIGGER ADMIN.TRG_SERVICE_USE_TYPES_BI
BEFORE INSERT ON ADMIN.ServiceUseTypes
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_SERVICE_USE_TYPES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- ===================== CREATE SETTINGS TABLES =====================

PROMPT ⚙️  Creando Tablas de Configuración...

-- THEME SETTINGS
CREATE TABLE ADMIN.ThemeSettings (
    ID NUMBER PRIMARY KEY,
    NAME NVARCHAR2(100) NOT NULL,
    DESCRIPTION NVARCHAR2(500),
    COLOR_PRIMARY NVARCHAR2(7) NOT NULL,
    COLOR_SECONDARY NVARCHAR2(7) NOT NULL,
    COLOR_ACCENT NVARCHAR2(7) NOT NULL,
    COLOR_INTERMEDIATE NVARCHAR2(7) NOT NULL,
    COLOR_SUCCESS NVARCHAR2(7) NOT NULL,
    COLOR_ERROR NVARCHAR2(7) NOT NULL,
    COLOR_WARNING NVARCHAR2(7) NOT NULL,
    COLOR_INFO NVARCHAR2(7) NOT NULL,
    BG_PRIMARY NVARCHAR2(7) NOT NULL,
    BG_SECONDARY NVARCHAR2(7) NOT NULL,
    TEXT_PRIMARY NVARCHAR2(7) NOT NULL,
    TEXT_SECONDARY NVARCHAR2(7) NOT NULL,
    SCROLLBAR_GRADIENT_START NVARCHAR2(7) NOT NULL,
    SCROLLBAR_GRADIENT_END NVARCHAR2(7) NOT NULL,
    SCROLLBAR_HOVER_START NVARCHAR2(7) NOT NULL,
    SCROLLBAR_HOVER_END NVARCHAR2(7) NOT NULL,
    IS_DEFAULT_THEME NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Sequence for ThemeSettings
CREATE SEQUENCE ADMIN.SEQ_THEME_SETTINGS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for ThemeSettings
CREATE OR REPLACE TRIGGER ADMIN.TRG_THEME_SETTINGS_BI
BEFORE INSERT ON ADMIN.ThemeSettings
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_THEME_SETTINGS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- SYSTEM SETTINGS
CREATE TABLE ADMIN.SystemSettings (
    ID NUMBER PRIMARY KEY,
    SETTING_KEY NVARCHAR2(100) NOT NULL UNIQUE,
    SETTING_VALUE NVARCHAR2(1000),
    SETTING_TYPE NVARCHAR2(50) NOT NULL,
    DESCRIPTION NVARCHAR2(500),
    IS_ENCRYPTED NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Sequence for SystemSettings
CREATE SEQUENCE ADMIN.SEQ_SYSTEM_SETTINGS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for SystemSettings
CREATE OR REPLACE TRIGGER ADMIN.TRG_SYSTEM_SETTINGS_BI
BEFORE INSERT ON ADMIN.SystemSettings
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_SYSTEM_SETTINGS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- ===================== CREATE SYSTEM TABLES =====================

PROMPT 🔐 Creando Tablas del Sistema...

CREATE TABLE ADMIN.Modules (
    ID NUMBER PRIMARY KEY,
    NAME NVARCHAR2(100) NOT NULL,
    CODE NVARCHAR2(20) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Sequence for Modules
CREATE SEQUENCE ADMIN.SEQ_MODULES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for Modules
CREATE OR REPLACE TRIGGER ADMIN.TRG_MODULES_BI
BEFORE INSERT ON ADMIN.Modules
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_MODULES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE ADMIN.Forms (
    ID NUMBER PRIMARY KEY,
    NAME NVARCHAR2(100) NOT NULL,
    CODE NVARCHAR2(50) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Sequence for Forms
CREATE SEQUENCE ADMIN.SEQ_FORMS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for Forms
CREATE OR REPLACE TRIGGER ADMIN.TRG_FORMS_BI
BEFORE INSERT ON ADMIN.Forms
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_FORMS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE ADMIN.FormModules (
    ID NUMBER PRIMARY KEY,
    FORM_ID NUMBER NOT NULL,
    MODULE_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_FORMMODULES_FORM FOREIGN KEY (FORM_ID) REFERENCES ADMIN.Forms(ID) ON DELETE CASCADE,
    CONSTRAINT FK_FORMMODULES_MODULE FOREIGN KEY (MODULE_ID) REFERENCES ADMIN.Modules(ID) ON DELETE CASCADE,
    CONSTRAINT UQ_FORM_MODULES UNIQUE (FORM_ID, MODULE_ID)
);

-- Sequence for FormModules
CREATE SEQUENCE ADMIN.SEQ_FORM_MODULES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for FormModules
CREATE OR REPLACE TRIGGER ADMIN.TRG_FORM_MODULES_BI
BEFORE INSERT ON ADMIN.FormModules
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_FORM_MODULES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE ADMIN.Permissions (
    ID NUMBER PRIMARY KEY,
    CAN_READ NUMBER(1) DEFAULT 0 NOT NULL,
    CAN_CREATE NUMBER(1) DEFAULT 0 NOT NULL,
    CAN_UPDATE NUMBER(1) DEFAULT 0 NOT NULL,
    CAN_DELETE NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Sequence for Permissions
CREATE SEQUENCE ADMIN.SEQ_PERMISSIONS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for Permissions
CREATE OR REPLACE TRIGGER ADMIN.TRG_PERMISSIONS_BI
BEFORE INSERT ON ADMIN.Permissions
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_PERMISSIONS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE ADMIN.Roles (
    ID NUMBER PRIMARY KEY,
    NAME NVARCHAR2(100) NOT NULL,
    CODE NVARCHAR2(20) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Sequence for Roles
CREATE SEQUENCE ADMIN.SEQ_ROLES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for Roles
CREATE OR REPLACE TRIGGER ADMIN.TRG_ROLES_BI
BEFORE INSERT ON ADMIN.Roles
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_ROLES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE ADMIN.Users (
    ID NUMBER PRIMARY KEY,
    USERNAME NVARCHAR2(50) NOT NULL UNIQUE,
    EMAIL NVARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD NVARCHAR2(255) NOT NULL,
    ALLOWED_TABS CLOB,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Sequence for Users
CREATE SEQUENCE ADMIN.SEQ_USERS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for Users
CREATE OR REPLACE TRIGGER ADMIN.TRG_USERS_BI
BEFORE INSERT ON ADMIN.Users
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_USERS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE ADMIN.RolUsers (
    ID NUMBER PRIMARY KEY,
    ROLE_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_ROLEUSERS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ADMIN.Roles(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ROLEUSERS_USER FOREIGN KEY (USER_ID) REFERENCES ADMIN.Users(ID) ON DELETE CASCADE,
    CONSTRAINT UQ_ROLE_USERS UNIQUE (ROLE_ID, USER_ID)
);

-- Sequence for RolUsers
CREATE SEQUENCE ADMIN.SEQ_ROL_USERS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for RolUsers
CREATE OR REPLACE TRIGGER ADMIN.TRG_ROL_USERS_BI
BEFORE INSERT ON ADMIN.RolUsers
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_ROL_USERS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE ADMIN.RolFormPermis (
    ID NUMBER PRIMARY KEY,
    ROLE_ID NUMBER NOT NULL,
    FORM_ID NUMBER NOT NULL,
    PERMISSION_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_ROLEFORMPERMISSIONS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ADMIN.Roles(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ROLEFORMPERMISSIONS_FORM FOREIGN KEY (FORM_ID) REFERENCES ADMIN.Forms(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ROLEFORMPERMISSIONS_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES ADMIN.Permissions(ID) ON DELETE CASCADE,
    CONSTRAINT UQ_ROLE_FORM_PERMISSIONS UNIQUE (ROLE_ID, FORM_ID, PERMISSION_ID)
);

-- Sequence for RolFormPermis
CREATE SEQUENCE ADMIN.SEQ_ROL_FORM_PERMIS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for RolFormPermis
CREATE OR REPLACE TRIGGER ADMIN.TRG_ROL_FORM_PERMIS_BI
BEFORE INSERT ON ADMIN.RolFormPermis
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_ROL_FORM_PERMIS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- ===================== CREATE BUSINESS TABLES =====================

PROMPT 🏢 Creando Tablas de Negocio...

-- BRANCHES (Sucursales)
CREATE TABLE ADMIN.Branches (
    ID NUMBER PRIMARY KEY,
    NAME NVARCHAR2(200) NOT NULL,
    CODE NVARCHAR2(20) NOT NULL UNIQUE,
    ADDRESS NVARCHAR2(500) NOT NULL,
    PHONE NVARCHAR2(20) NOT NULL,
    CITY NVARCHAR2(100) NOT NULL,
    STATE NVARCHAR2(100) NOT NULL,
    IS_MAIN NUMBER(1) DEFAULT 0 NOT NULL,
    COLOR_PRIMARY NVARCHAR2(20),
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Sequence for Branches
CREATE SEQUENCE ADMIN.SEQ_BRANCHES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for Branches
CREATE OR REPLACE TRIGGER ADMIN.TRG_BRANCHES_BI
BEFORE INSERT ON ADMIN.Branches
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_BRANCHES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- CLIENTS (Clientes) - DOCUMENT_TYPE es NUMBER (enum: 1=CC, 2=TI, 3=RC, 4=CE)
CREATE TABLE ADMIN.Clients (
    ID NUMBER PRIMARY KEY,
    CLIENT_NUMBER NVARCHAR2(50) NOT NULL UNIQUE,
    DOCUMENT_TYPE NUMBER(10) NOT NULL,
    DOCUMENT_NUMBER NVARCHAR2(50) NOT NULL UNIQUE,
    FULL_NAME NVARCHAR2(200) NOT NULL,
    EMAIL NVARCHAR2(255) NOT NULL UNIQUE,
    PHONE NVARCHAR2(20) NOT NULL,
    MOBILE NVARCHAR2(20) NOT NULL,
    ADDRESS NVARCHAR2(500) NOT NULL,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Sequence for Clients
CREATE SEQUENCE ADMIN.SEQ_CLIENTS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for Clients
CREATE OR REPLACE TRIGGER ADMIN.TRG_CLIENTS_BI
BEFORE INSERT ON ADMIN.Clients
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_CLIENTS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- HOLIDAYS (Festivos) - Moved here after Branches creation
CREATE TABLE ADMIN.Holidays (
    ID NUMBER PRIMARY KEY,
    HOLIDAY_DATE DATE NOT NULL,
    HOLIDAY_NAME NVARCHAR2(200) NOT NULL,
    HOLIDAY_TYPE NVARCHAR2(50) NOT NULL,
    BRANCH_ID NUMBER,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_HOLIDAYS_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES ADMIN.Branches(ID)
);

-- Sequence for Holidays
CREATE SEQUENCE ADMIN.SEQ_HOLIDAYS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for Holidays
CREATE OR REPLACE TRIGGER ADMIN.TRG_HOLIDAYS_BI
BEFORE INSERT ON ADMIN.Holidays
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_HOLIDAYS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- APPOINTMENT TYPES
-- NOTA: NO usar GENERATED ALWAYS AS IDENTITY - usar trigger/sequence para evitar conflictos
CREATE TABLE ADMIN.AppointmentTypes (
    ID NUMBER PRIMARY KEY,
    CODE NVARCHAR2(50) NOT NULL UNIQUE,
    NAME NVARCHAR2(100) NOT NULL,
    DESCRIPTION NVARCHAR2(500),
    ICON_NAME NVARCHAR2(100),
    COLOR_PRIMARY NVARCHAR2(20),
    COLOR_SECONDARY NVARCHAR2(20),
    ESTIMATED_TIME_MINUTES NUMBER DEFAULT 120 NOT NULL,
    REQUIRES_DOCUMENTATION NUMBER(1) DEFAULT 1 NOT NULL,
    DISPLAY_ORDER NUMBER DEFAULT 0,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

-- Sequence for AppointmentTypes
CREATE SEQUENCE ADMIN.SEQ_APPOINTMENT_TYPES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for AppointmentTypes
CREATE OR REPLACE TRIGGER ADMIN.TRG_APPOINTMENT_TYPES_BI
BEFORE INSERT ON ADMIN.AppointmentTypes
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_APPOINTMENT_TYPES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- APPOINTMENTS (Citas)
CREATE TABLE ADMIN.Appointments (
    ID NUMBER PRIMARY KEY,
    APPOINTMENT_NUMBER NVARCHAR2(50) NOT NULL UNIQUE,
    APPOINTMENT_DATE DATE NOT NULL,
    APPOINTMENT_TIME NVARCHAR2(20),
    STATUS_ID NUMBER NOT NULL,
    NOTES NVARCHAR2(1000),
    CANCELLATION_REASON NVARCHAR2(500),
    COMPLETED_DATE DATE,
    CLIENT_ID NUMBER NOT NULL,
    BRANCH_ID NUMBER NOT NULL,
    APPOINTMENT_TYPE_ID NUMBER NOT NULL,
    IS_ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_APPOINTMENTS_CLIENTS FOREIGN KEY (CLIENT_ID) REFERENCES ADMIN.Clients(ID),
    CONSTRAINT FK_APPOINTMENTS_BRANCHES FOREIGN KEY (BRANCH_ID) REFERENCES ADMIN.Branches(ID),
    CONSTRAINT FK_APPOINTMENTS_APPOINTMENT_TYPES FOREIGN KEY (APPOINTMENT_TYPE_ID) REFERENCES ADMIN.AppointmentTypes(ID),
    CONSTRAINT FK_APPOINTMENTS_STATUS FOREIGN KEY (STATUS_ID) REFERENCES ADMIN.AppointmentStatuses(ID)
);

-- Sequence for Appointments
CREATE SEQUENCE ADMIN.SEQ_APPOINTMENTS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for Appointments
CREATE OR REPLACE TRIGGER ADMIN.TRG_APPOINTMENTS_BI
BEFORE INSERT ON ADMIN.Appointments
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_APPOINTMENTS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- AVAILABLE TIMES
CREATE TABLE ADMIN.AvailableTimes (
    ID NUMBER PRIMARY KEY,
    TIME NVARCHAR2(20) NOT NULL,
    BRANCH_ID NUMBER NOT NULL,
    APPOINTMENT_TYPE_ID NUMBER,
    MAX_APPOINTMENTS_PER_SLOT NUMBER DEFAULT 1,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_AVAILABLETIMES_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES ADMIN.Branches(ID),
    CONSTRAINT FK_AVAILABLETIMES_APPOINTMENTTYPE FOREIGN KEY (APPOINTMENT_TYPE_ID) REFERENCES ADMIN.AppointmentTypes(ID)
);

-- Sequence for AvailableTimes
CREATE SEQUENCE ADMIN.SEQ_AVAILABLE_TIMES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for AvailableTimes
CREATE OR REPLACE TRIGGER ADMIN.TRG_AVAILABLE_TIMES_BI
BEFORE INSERT ON ADMIN.AvailableTimes
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_AVAILABLE_TIMES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- APPOINTMENT DOCUMENTS
CREATE TABLE ADMIN.AppointmentDocuments (
    ID NUMBER PRIMARY KEY,
    APPOINTMENT_ID NUMBER NOT NULL,
    DOCUMENT_NAME NVARCHAR2(500) NOT NULL,
    DOCUMENT_TYPE NVARCHAR2(100),
    FILE_PATH NVARCHAR2(1000) NOT NULL,
    FILE_SIZE NUMBER,
    UPLOADED_BY NUMBER,
    DESCRIPTION NVARCHAR2(1000),
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_APPTDOCS_APPOINTMENT FOREIGN KEY (APPOINTMENT_ID) REFERENCES ADMIN.Appointments(ID) ON DELETE CASCADE,
    CONSTRAINT FK_APPTDOCS_USER FOREIGN KEY (UPLOADED_BY) REFERENCES ADMIN.Users(ID)
);

-- Sequence for AppointmentDocuments
CREATE SEQUENCE ADMIN.SEQ_APPOINTMENT_DOCUMENTS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for AppointmentDocuments
CREATE OR REPLACE TRIGGER ADMIN.TRG_APPOINTMENT_DOCUMENTS_BI
BEFORE INSERT ON ADMIN.AppointmentDocuments
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_APPOINTMENT_DOCUMENTS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- NOTIFICATIONS (Sistema de notificaciones para USERS y CLIENTS)
-- Soporta notificaciones tanto para usuarios (admins) como para clientes
-- USER_ID: Para notificaciones IN_APP dirigidas a admins
-- CLIENT_ID: Para notificaciones EMAIL/WHATSAPP dirigidas a clientes
CREATE TABLE ADMIN.Notifications (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,  -- Nullable: para notificaciones IN_APP de ADMINS
    CLIENT_ID NUMBER,  -- Nullable: para notificaciones EMAIL/WHATSAPP de CLIENTES
    APPOINTMENT_ID NUMBER,
    TYPE NVARCHAR2(20) NOT NULL,  -- EMAIL, WHATSAPP, IN_APP
    TITLE NVARCHAR2(200) NOT NULL,
    MESSAGE NVARCHAR2(2000) NOT NULL,
    STATUS NVARCHAR2(20) NOT NULL,  -- PENDING, SENT, FAILED
    SENT_AT TIMESTAMP(7),
    READ_AT TIMESTAMP(7),
    IS_READ NUMBER(1) DEFAULT 0 NOT NULL,
    ERROR_MESSAGE NVARCHAR2(1000),
    METADATA CLOB,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_NOTIFICATIONS_USER FOREIGN KEY (USER_ID) REFERENCES ADMIN.Users(ID) ON DELETE CASCADE,
    CONSTRAINT FK_NOTIFICATIONS_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES ADMIN.Clients(ID) ON DELETE CASCADE,
    CONSTRAINT FK_NOTIFICATIONS_APPOINTMENT FOREIGN KEY (APPOINTMENT_ID) REFERENCES ADMIN.Appointments(ID) ON DELETE SET NULL,
    -- Constraint: debe tener USER_ID O CLIENT_ID (no ambos, no ninguno)
    CONSTRAINT CHK_NOTIFICATION_RECIPIENT CHECK ((USER_ID IS NOT NULL AND CLIENT_ID IS NULL) OR (USER_ID IS NULL AND CLIENT_ID IS NOT NULL))
);

-- Sequence for Notifications
CREATE SEQUENCE ADMIN.SEQ_NOTIFICATIONS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger for Notifications
CREATE OR REPLACE TRIGGER ADMIN.TRG_NOTIFICATIONS_BI
BEFORE INSERT ON ADMIN.Notifications
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_NOTIFICATIONS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- USER_APPOINTMENT_TYPE_ASSIGNMENTS (Asignaciones de empleados a tipos de cita)
-- NOTA: NO usar GENERATED ALWAYS AS IDENTITY - usar trigger/sequence para evitar conflictos
CREATE TABLE ADMIN.UserAppointmentTypeAssignments (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    APPOINTMENT_TYPE_ID NUMBER NOT NULL,
    ASSIGNED_BY_USER_ID NUMBER,
    ASSIGNED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(7),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_UATA_USER FOREIGN KEY (USER_ID) REFERENCES ADMIN.Users(ID) ON DELETE CASCADE,
    CONSTRAINT FK_UATA_APPT_TYPE FOREIGN KEY (APPOINTMENT_TYPE_ID) REFERENCES ADMIN.AppointmentTypes(ID) ON DELETE CASCADE,
    CONSTRAINT FK_UATA_ASSIGNED_BY FOREIGN KEY (ASSIGNED_BY_USER_ID) REFERENCES ADMIN.Users(ID) ON DELETE SET NULL,
    CONSTRAINT UQ_USER_APPT_TYPE UNIQUE (USER_ID, APPOINTMENT_TYPE_ID)
);

-- Secuencia y trigger para UserAppointmentTypeAssignments
CREATE SEQUENCE ADMIN.SEQ_USER_APPT_TYPE_ASSIGNS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER ADMIN.TRG_USER_APPT_TYPE_ASSIGNS_BI
BEFORE INSERT ON ADMIN.UserAppointmentTypeAssignments
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL OR :NEW.ID = 0 THEN
        SELECT SEQ_USER_APPT_TYPE_ASSIGNS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Índices para UserAppointmentTypeAssignments
CREATE INDEX IDX_UATA_USER_ID ON ADMIN.UserAppointmentTypeAssignments(USER_ID);
CREATE INDEX IDX_UATA_APPT_TYPE_ID ON ADMIN.UserAppointmentTypeAssignments(APPOINTMENT_TYPE_ID);
CREATE INDEX IDX_UATA_ACTIVE ON ADMIN.UserAppointmentTypeAssignments(IS_ACTIVE);
CREATE INDEX IDX_UATA_USER_ACTIVE ON ADMIN.UserAppointmentTypeAssignments(USER_ID, IS_ACTIVE);

-- Vista optimizada para consultas de asignaciones
CREATE OR REPLACE VIEW ADMIN.VW_USER_ASSIGNMENTS_DETAIL AS
SELECT
    uata.ID AS ASSIGNMENT_ID,
    uata.USER_ID,
    u.USERNAME,
    u.EMAIL AS USER_EMAIL,
    uata.APPOINTMENT_TYPE_ID,
    at.CODE AS APPOINTMENT_TYPE_CODE,
    at.NAME AS APPOINTMENT_TYPE_NAME,
    at.ICON_NAME,
    at.COLOR_PRIMARY,
    uata.ASSIGNED_AT,
    uata.IS_ACTIVE AS ASSIGNMENT_ACTIVE,
    admin_user.USERNAME AS ASSIGNED_BY_USERNAME,
    uata.CREATED_AT,
    uata.UPDATED_AT
FROM ADMIN.UserAppointmentTypeAssignments uata
INNER JOIN ADMIN.Users u ON uata.USER_ID = u.ID
INNER JOIN ADMIN.AppointmentTypes at ON uata.APPOINTMENT_TYPE_ID = at.ID
LEFT JOIN ADMIN.Users admin_user ON uata.ASSIGNED_BY_USER_ID = admin_user.ID
WHERE uata.IS_ACTIVE = 1 AND u.IS_ACTIVE = 1 AND at.IS_ACTIVE = 1;

-- ===================== INSERT CATALOG DATA =====================

PROMPT 📊 Insertando Datos de Catálogo...

-- APPOINTMENT STATUSES
INSERT INTO ADMIN.AppointmentStatuses (CODE, NAME, DESCRIPTION, COLOR_PRIMARY, COLOR_SECONDARY, COLOR_TEXT, ICON_NAME, DISPLAY_ORDER, ALLOW_CANCELLATION, IS_FINAL_STATE)
VALUES ('PENDING', 'Pendiente', 'Cita agendada, esperando confirmación', '#F59E0B', '#FCD34D', '#FFFFFF', 'clock', 1, 1, 0);

INSERT INTO ADMIN.AppointmentStatuses (CODE, NAME, DESCRIPTION, COLOR_PRIMARY, COLOR_SECONDARY, COLOR_TEXT, ICON_NAME, DISPLAY_ORDER, ALLOW_CANCELLATION, IS_FINAL_STATE)
VALUES ('CONFIRMED', 'Confirmada', 'Cita confirmada por el cliente', '#3B82F6', '#60A5FA', '#FFFFFF', 'bell', 2, 1, 0);

INSERT INTO ADMIN.AppointmentStatuses (CODE, NAME, DESCRIPTION, COLOR_PRIMARY, COLOR_SECONDARY, COLOR_TEXT, ICON_NAME, DISPLAY_ORDER, ALLOW_CANCELLATION, IS_FINAL_STATE)
VALUES ('IN_PROGRESS', 'En Progreso', 'Técnico atendiendo la cita', '#8B5CF6', '#A78BFA', '#FFFFFF', 'spinner', 3, 0, 0);

INSERT INTO ADMIN.AppointmentStatuses (CODE, NAME, DESCRIPTION, COLOR_PRIMARY, COLOR_SECONDARY, COLOR_TEXT, ICON_NAME, DISPLAY_ORDER, ALLOW_CANCELLATION, IS_FINAL_STATE)
VALUES ('COMPLETED', 'Completada', 'Cita completada exitosamente', '#10B981', '#34D399', '#FFFFFF', 'check-circle', 4, 0, 1);

INSERT INTO ADMIN.AppointmentStatuses (CODE, NAME, DESCRIPTION, COLOR_PRIMARY, COLOR_SECONDARY, COLOR_TEXT, ICON_NAME, DISPLAY_ORDER, ALLOW_CANCELLATION, IS_FINAL_STATE)
VALUES ('CANCELLED', 'Cancelada', 'Cita cancelada por el cliente o el sistema', '#EF4444', '#F87171', '#FFFFFF', 'times-circle', 5, 0, 1);

INSERT INTO ADMIN.AppointmentStatuses (CODE, NAME, DESCRIPTION, COLOR_PRIMARY, COLOR_SECONDARY, COLOR_TEXT, ICON_NAME, DISPLAY_ORDER, ALLOW_CANCELLATION, IS_FINAL_STATE)
VALUES ('NO_SHOW', 'No Asistió', 'Cliente no se presentó a la cita', '#6B7280', '#9CA3AF', '#FFFFFF', 'exclamation-triangle', 6, 0, 1);

-- PROJECT TYPES
INSERT INTO ADMIN.ProjectTypes (CODE, NAME, DESCRIPTION, ICON_NAME, COLOR_PRIMARY, DISPLAY_ORDER)
VALUES ('URBANIZATION', 'Urbanización', 'Proyecto de urbanización residencial', 'city', '#3B82F6', 1);

INSERT INTO ADMIN.ProjectTypes (CODE, NAME, DESCRIPTION, ICON_NAME, COLOR_PRIMARY, DISPLAY_ORDER)
VALUES ('RESIDENTIAL_COMPLEX', 'Conjunto Residencial', 'Conjunto de viviendas', 'building', '#10B981', 2);

INSERT INTO ADMIN.ProjectTypes (CODE, NAME, DESCRIPTION, ICON_NAME, COLOR_PRIMARY, DISPLAY_ORDER)
VALUES ('COMMERCIAL_CENTER', 'Centro Comercial', 'Centro comercial o mall', 'shopping-cart', '#F59E0B', 3);

INSERT INTO ADMIN.ProjectTypes (CODE, NAME, DESCRIPTION, ICON_NAME, COLOR_PRIMARY, DISPLAY_ORDER)
VALUES ('INDUSTRIAL_ZONE', 'Zona Industrial', 'Parque o zona industrial', 'industry', '#6B7280', 4);

INSERT INTO ADMIN.ProjectTypes (CODE, NAME, DESCRIPTION, ICON_NAME, COLOR_PRIMARY, DISPLAY_ORDER)
VALUES ('TOURIST_COMPLEX', 'Complejo Turístico', 'Hotel, resort u otro complejo turístico', 'umbrella-beach', '#8B5CF6', 5);

-- PROPERTY TYPES
INSERT INTO ADMIN.PropertyTypes (CODE, NAME, ICON_NAME, DISPLAY_ORDER) VALUES ('HOUSE', 'Casa', 'home', 1);
INSERT INTO ADMIN.PropertyTypes (CODE, NAME, ICON_NAME, DISPLAY_ORDER) VALUES ('APARTMENT', 'Apartamento', 'building', 2);
INSERT INTO ADMIN.PropertyTypes (CODE, NAME, ICON_NAME, DISPLAY_ORDER) VALUES ('COMMERCIAL', 'Local Comercial', 'store', 3);
INSERT INTO ADMIN.PropertyTypes (CODE, NAME, ICON_NAME, DISPLAY_ORDER) VALUES ('OFFICE', 'Oficina', 'briefcase', 4);
INSERT INTO ADMIN.PropertyTypes (CODE, NAME, ICON_NAME, DISPLAY_ORDER) VALUES ('WAREHOUSE', 'Bodega', 'warehouse', 5);

-- SERVICE USE TYPES
INSERT INTO ADMIN.ServiceUseTypes (CODE, NAME, DISPLAY_ORDER) VALUES ('RESIDENTIAL', 'Residencial', 1);
INSERT INTO ADMIN.ServiceUseTypes (CODE, NAME, DISPLAY_ORDER) VALUES ('COMMERCIAL', 'Comercial', 2);
INSERT INTO ADMIN.ServiceUseTypes (CODE, NAME, DISPLAY_ORDER) VALUES ('INDUSTRIAL', 'Industrial', 3);
INSERT INTO ADMIN.ServiceUseTypes (CODE, NAME, DISPLAY_ORDER) VALUES ('OFFICIAL', 'Oficial', 4);

-- ===================== INSERT SETTINGS DATA =====================

PROMPT ⚙️  Insertando Configuración...

-- THEME SETTINGS (ElectroHuila Default Theme)
INSERT INTO ADMIN.ThemeSettings (
    NAME, DESCRIPTION,
    COLOR_PRIMARY, COLOR_SECONDARY, COLOR_ACCENT, COLOR_INTERMEDIATE,
    COLOR_SUCCESS, COLOR_ERROR, COLOR_WARNING, COLOR_INFO,
    BG_PRIMARY, BG_SECONDARY, TEXT_PRIMARY, TEXT_SECONDARY,
    SCROLLBAR_GRADIENT_START, SCROLLBAR_GRADIENT_END,
    SCROLLBAR_HOVER_START, SCROLLBAR_HOVER_END,
    IS_DEFAULT_THEME
) VALUES (
    'ElectroHuila Default',
    'Tema corporativo por defecto de ElectroHuila con colores institucionales',
    '#203461', '#1797D5', '#56C2E1', '#1A6192',
    '#22C55E', '#EF4444', '#F59E0B', '#3B82F6',
    '#FFFFFF', '#F9FAFB', '#111827', '#6B7280',
    '#1797D5', '#56C2E1', '#203461', '#1797D5',
    1
);

-- SYSTEM SETTINGS
INSERT INTO ADMIN.SystemSettings (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION)
VALUES ('MAX_APPOINTMENTS_PER_DAY', '50', 'NUMBER', 'Máximo de citas por día por sucursal');

INSERT INTO ADMIN.SystemSettings (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION)
VALUES ('APPOINTMENT_CANCELLATION_HOURS', '24', 'NUMBER', 'Horas mínimas antes de la cita para poder cancelar');

INSERT INTO ADMIN.SystemSettings (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION)
VALUES ('EMAIL_NOTIFICATIONS_ENABLED', 'true', 'BOOLEAN', 'Habilitar notificaciones por correo electrónico');

INSERT INTO ADMIN.SystemSettings (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION)
VALUES ('SMS_NOTIFICATIONS_ENABLED', 'false', 'BOOLEAN', 'Habilitar notificaciones por SMS');

INSERT INTO ADMIN.SystemSettings (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION)
VALUES ('APPOINTMENT_REMINDER_HOURS', '24', 'NUMBER', 'Horas antes de la cita para enviar recordatorio');

INSERT INTO ADMIN.SystemSettings (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION)
VALUES ('BUSINESS_HOURS_START', '08:00', 'STRING', 'Hora de inicio de atención');

INSERT INTO ADMIN.SystemSettings (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION)
VALUES ('BUSINESS_HOURS_END', '17:00', 'STRING', 'Hora de fin de atención');

-- HOLIDAYS (Colombian holidays 2025)
PROMPT 🎉 Insertando Festivos Colombianos 2025...

INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-01-01', 'Año Nuevo', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-01-06', 'Día de los Reyes Magos', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-03-24', 'Día de San José', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-04-17', 'Jueves Santo', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-04-18', 'Viernes Santo', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-05-01', 'Día del Trabajo', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-06-02', 'Ascensión del Señor', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-06-23', 'Corpus Christi', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-06-30', 'Sagrado Corazón de Jesús', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-07-07', 'San Pedro y San Pablo', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-07-20', 'Día de la Independencia', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-08-07', 'Batalla de Boyacá', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-08-18', 'Asunción de la Virgen', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-10-13', 'Día de la Raza', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-11-03', 'Todos los Santos', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-11-17', 'Independencia de Cartagena', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-12-08', 'Inmaculada Concepción', 'NATIONAL');
INSERT INTO ADMIN.Holidays (HOLIDAY_DATE, HOLIDAY_NAME, HOLIDAY_TYPE) VALUES (DATE '2025-12-25', 'Navidad', 'NATIONAL');

-- ===================== INSERT SYSTEM DATA =====================

PROMPT 👤 Insertando Datos del Sistema...

-- MODULES
INSERT INTO ADMIN.Modules (NAME, CODE) VALUES ('User Management', 'USER_MGMT');
INSERT INTO ADMIN.Modules (NAME, CODE) VALUES ('Appointment Management', 'APPT_MGMT');
INSERT INTO ADMIN.Modules (NAME, CODE) VALUES ('Client Management', 'CLIENT_MGMT');
INSERT INTO ADMIN.Modules (NAME, CODE) VALUES ('Branch Management', 'BRANCH_MGMT');
INSERT INTO ADMIN.Modules (NAME, CODE) VALUES ('Configuration', 'CONFIG');

-- FORMS
INSERT INTO ADMIN.Forms (NAME, CODE) VALUES ('Appointments', 'APPOINTMENTS');
INSERT INTO ADMIN.Forms (NAME, CODE) VALUES ('Users', 'USERS');
INSERT INTO ADMIN.Forms (NAME, CODE) VALUES ('Roles', 'ROLES');
INSERT INTO ADMIN.Forms (NAME, CODE) VALUES ('Clients', 'CLIENTS');
INSERT INTO ADMIN.Forms (NAME, CODE) VALUES ('Branches', 'BRANCHES');
INSERT INTO ADMIN.Forms (NAME, CODE) VALUES ('Appointment Types', 'APPOINTMENT_TYPES');
INSERT INTO ADMIN.Forms (NAME, CODE) VALUES ('Available Times', 'AVAILABLE_TIMES');
INSERT INTO ADMIN.Forms (NAME, CODE) VALUES ('Permissions', 'PERMISSIONS');
INSERT INTO ADMIN.Forms (NAME, CODE) VALUES ('Theme Settings', 'THEME_SETTINGS');
INSERT INTO ADMIN.Forms (NAME, CODE) VALUES ('Festivos', 'HOLIDAYS');
INSERT INTO ADMIN.Forms (NAME, CODE) VALUES ('Plantillas de Notificación', 'NOTIFICATIONS');
INSERT INTO ADMIN.Forms (NAME, CODE) VALUES ('Configuración del Sistema', 'SETTINGS');
INSERT INTO ADMIN.Forms (NAME, CODE) VALUES ('Documentos de Citas', 'DOCUMENTS');

-- FORM-MODULE RELATIONSHIPS
INSERT INTO ADMIN.FormModules (FORM_ID, MODULE_ID) VALUES (1, 2);  -- Appointments -> Appointment Management
INSERT INTO ADMIN.FormModules (FORM_ID, MODULE_ID) VALUES (2, 1);  -- Users -> User Management
INSERT INTO ADMIN.FormModules (FORM_ID, MODULE_ID) VALUES (3, 1);  -- Roles -> User Management
INSERT INTO ADMIN.FormModules (FORM_ID, MODULE_ID) VALUES (4, 3);  -- Clients -> Client Management
INSERT INTO ADMIN.FormModules (FORM_ID, MODULE_ID) VALUES (5, 4);  -- Branches -> Branch Management
INSERT INTO ADMIN.FormModules (FORM_ID, MODULE_ID) VALUES (6, 2);  -- Appointment Types -> Appointment Management
INSERT INTO ADMIN.FormModules (FORM_ID, MODULE_ID) VALUES (7, 2);  -- Available Times -> Appointment Management
INSERT INTO ADMIN.FormModules (FORM_ID, MODULE_ID) VALUES (8, 5);  -- Permissions -> Configuration
INSERT INTO ADMIN.FormModules (FORM_ID, MODULE_ID) VALUES (9, 5);  -- Theme Settings -> Configuration
INSERT INTO ADMIN.FormModules (FORM_ID, MODULE_ID) VALUES (10, 5); -- Festivos -> Configuration
INSERT INTO ADMIN.FormModules (FORM_ID, MODULE_ID) VALUES (11, 5); -- Plantillas -> Configuration
INSERT INTO ADMIN.FormModules (FORM_ID, MODULE_ID) VALUES (12, 5); -- Settings -> Configuration
INSERT INTO ADMIN.FormModules (FORM_ID, MODULE_ID) VALUES (13, 2); -- Documents -> Appointment Management

-- PERMISSIONS
INSERT INTO ADMIN.Permissions (CAN_READ, CAN_CREATE, CAN_UPDATE, CAN_DELETE) VALUES (1, 1, 1, 1);
INSERT INTO ADMIN.Permissions (CAN_READ, CAN_CREATE, CAN_UPDATE, CAN_DELETE) VALUES (1, 1, 1, 0);
INSERT INTO ADMIN.Permissions (CAN_READ, CAN_CREATE, CAN_UPDATE, CAN_DELETE) VALUES (1, 1, 0, 0);
INSERT INTO ADMIN.Permissions (CAN_READ, CAN_CREATE, CAN_UPDATE, CAN_DELETE) VALUES (1, 0, 0, 0);
INSERT INTO ADMIN.Permissions (CAN_READ, CAN_CREATE, CAN_UPDATE, CAN_DELETE) VALUES (0, 0, 0, 0);

-- ROLES
INSERT INTO ADMIN.Roles (NAME, CODE) VALUES ('Super Administrator', 'SUPER_ADMIN');
INSERT INTO ADMIN.Roles (NAME, CODE) VALUES ('Administrator', 'ADMIN');
INSERT INTO ADMIN.Roles (NAME, CODE) VALUES ('Operator', 'OPERATOR');
INSERT INTO ADMIN.Roles (NAME, CODE) VALUES ('Receptionist', 'RECEPTIONIST');
INSERT INTO ADMIN.Roles (NAME, CODE) VALUES ('Technician', 'TECHNICIAN');

-- USERS with BCrypt hash for password "Admin123!"
INSERT INTO ADMIN.Users (USERNAME, EMAIL, PASSWORD) VALUES ('admin', 'admin@electrohuila.com', '$2a$11$Gf7YOiKPr7LkKSeyy0k5Nu3zLG/bpqKl8N1SfqEjhCz6yblLlvlQe');
INSERT INTO ADMIN.Users (USERNAME, EMAIL, PASSWORD) VALUES ('operator1', 'operator1@electrohuila.com', 'Operator123!');
INSERT INTO ADMIN.Users (USERNAME, EMAIL, PASSWORD) VALUES ('reception', 'reception@electrohuila.com', '$2a$11$Gf7YOiKPr7LkKSeyy0k5Nu3zLG/bpqKl8N1SfqEjhCz6yblLlvlQe');
INSERT INTO ADMIN.Users (USERNAME, EMAIL, PASSWORD) VALUES ('tech1', 'tech1@electrohuila.com', '$2a$11$Gf7YOiKPr7LkKSeyy0k5Nu3zLG/bpqKl8N1SfqEjhCz6yblLlvlQe');
INSERT INTO ADMIN.Users (USERNAME, EMAIL, PASSWORD) VALUES ('supervisor', 'supervisor@electrohuila.com', '$2a$11$Gf7YOiKPr7LkKSeyy0k5Nu3zLG/bpqKl8N1SfqEjhCz6yblLlvlQe');

-- USER-ROLE RELATIONSHIPS
INSERT INTO ADMIN.RolUsers (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO ADMIN.RolUsers (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO ADMIN.RolUsers (USER_ID, ROLE_ID) VALUES (3, 4);
INSERT INTO ADMIN.RolUsers (USER_ID, ROLE_ID) VALUES (4, 5);
INSERT INTO ADMIN.RolUsers (USER_ID, ROLE_ID) VALUES (5, 3);

-- ROLE-FORM PERMISSIONS
-- Super Admin (Role 1) - Full access to all forms
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (1, 1, 1);  -- Appointments
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (1, 2, 1);  -- Users
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (1, 3, 1);  -- Roles
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (1, 4, 1);  -- Clients
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (1, 5, 1);  -- Branches
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (1, 6, 1);  -- Appointment Types
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (1, 7, 1);  -- Available Times
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (1, 8, 1);  -- Permissions
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (1, 9, 1);  -- Theme Settings
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (1, 10, 1); -- Festivos
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (1, 11, 1); -- Plantillas
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (1, 12, 1); -- Settings
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (1, 13, 1); -- Documents

-- Admin (Role 2) - Can read/create/update (no delete)
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (2, 1, 2);  -- Appointments
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (2, 4, 2);  -- Clients
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (2, 9, 2);  -- Theme Settings
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (2, 10, 2); -- Festivos (CRU)
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (2, 11, 2); -- Plantillas (CRU)
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (2, 12, 4); -- Settings (Read only)
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (2, 13, 2); -- Documents (CRU)

-- Operator (Role 3) - Read on holidays/settings, CRU on documents
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (3, 10, 4); -- Festivos (Read only)
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (3, 12, 4); -- Settings (Read only)
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (3, 13, 2); -- Documents (CRU)

-- Receptionist (Role 4) - Can read/create appointments and read clients
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (4, 1, 3);  -- Appointments
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (4, 4, 4);  -- Clients (read only)
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (4, 10, 4); -- Festivos (Read only)
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (4, 13, 3); -- Documents (Create + Read)

-- Technician (Role 5) - Can read/create/update appointments
INSERT INTO ADMIN.RolFormPermis (ROLE_ID, FORM_ID, PERMISSION_ID) VALUES (5, 1, 2);  -- Appointments

-- ===================== INSERT BUSINESS DATA =====================

PROMPT 🏢 Insertando Datos de Negocio...

-- BRANCHES
INSERT INTO ADMIN.Branches (NAME, CODE, ADDRESS, PHONE, CITY, STATE, IS_MAIN, COLOR_PRIMARY) VALUES
    ('Sede Principal Neiva', 'NEI01', 'Carrera 5 # 10-55 Centro', '6088664600', 'Neiva', 'Huila', 1, '#3B82F6');
INSERT INTO ADMIN.Branches (NAME, CODE, ADDRESS, PHONE, CITY, STATE, IS_MAIN, COLOR_PRIMARY) VALUES
    ('Sede Norte Neiva', 'NEI02', 'Calle 44 # 3-25 Norte', '6088664646', 'Neiva', 'Huila', 0, '#10B981');
INSERT INTO ADMIN.Branches (NAME, CODE, ADDRESS, PHONE, CITY, STATE, IS_MAIN, COLOR_PRIMARY) VALUES
    ('Sede Pitalito', 'PIT01', 'Carrera 3 # 7-89', '6088364455', 'Pitalito', 'Huila', 0, '#F59E0B');
INSERT INTO ADMIN.Branches (NAME, CODE, ADDRESS, PHONE, CITY, STATE, IS_MAIN, COLOR_PRIMARY) VALUES
    ('Sede La Plata', 'LAP01', 'Calle 5 # 4-12', '6088274488', 'La Plata', 'Huila', 0, '#8B5CF6');
INSERT INTO ADMIN.Branches (NAME, CODE, ADDRESS, PHONE, CITY, STATE, IS_MAIN, COLOR_PRIMARY) VALUES
    ('Sede Garzón', 'GAR01', 'Carrera 8 # 6-34', '6088332299', 'Garzón', 'Huila', 0, '#EF4444');

-- APPOINTMENT TYPES
INSERT INTO ADMIN.AppointmentTypes (CODE, NAME, DESCRIPTION, ICON_NAME, COLOR_PRIMARY, COLOR_SECONDARY, ESTIMATED_TIME_MINUTES, REQUIRES_DOCUMENTATION, DISPLAY_ORDER) VALUES
    ('CONEXION_NUEVA', 'Conexión Nueva', 'Solicitud de nueva conexión eléctrica', 'plug', '#3B82F6', '#60A5FA', 45, 1, 1);
INSERT INTO ADMIN.AppointmentTypes (CODE, NAME, DESCRIPTION, ICON_NAME, COLOR_PRIMARY, COLOR_SECONDARY, ESTIMATED_TIME_MINUTES, REQUIRES_DOCUMENTATION, DISPLAY_ORDER) VALUES
    ('RECONEXION', 'Reconexión', 'Reconexión del servicio eléctrico', 'bolt', '#10B981', '#34D399', 30, 1, 2);
INSERT INTO ADMIN.AppointmentTypes (CODE, NAME, DESCRIPTION, ICON_NAME, COLOR_PRIMARY, COLOR_SECONDARY, ESTIMATED_TIME_MINUTES, REQUIRES_DOCUMENTATION, DISPLAY_ORDER) VALUES
    ('CAMBIO_MEDIDOR', 'Cambio de Medidor', 'Cambio o instalación de nuevo medidor', 'tachometer-alt', '#F59E0B', '#FCD34D', 60, 1, 3);
INSERT INTO ADMIN.AppointmentTypes (CODE, NAME, DESCRIPTION, ICON_NAME, COLOR_PRIMARY, COLOR_SECONDARY, ESTIMATED_TIME_MINUTES, REQUIRES_DOCUMENTATION, DISPLAY_ORDER) VALUES
    ('REVISION_TECNICA', 'Revisión Técnica', 'Revisión técnica de instalaciones', 'wrench', '#8B5CF6', '#A78BFA', 90, 1, 4);
INSERT INTO ADMIN.AppointmentTypes (CODE, NAME, DESCRIPTION, ICON_NAME, COLOR_PRIMARY, COLOR_SECONDARY, ESTIMATED_TIME_MINUTES, REQUIRES_DOCUMENTATION, DISPLAY_ORDER) VALUES
    ('TRASLADO_MEDIDOR', 'Traslado de Medidor', 'Traslado de medidor a nueva ubicación', 'box-open', '#6B7280', '#9CA3AF', 120, 1, 5);
INSERT INTO ADMIN.AppointmentTypes (CODE, NAME, DESCRIPTION, ICON_NAME, COLOR_PRIMARY, COLOR_SECONDARY, ESTIMATED_TIME_MINUTES, REQUIRES_DOCUMENTATION, DISPLAY_ORDER) VALUES
    ('CONSULTA_GENERAL', 'Consulta General', 'Consulta general sobre servicios', 'comments', '#EC4899', '#F472B6', 20, 0, 6);
INSERT INTO ADMIN.AppointmentTypes (CODE, NAME, DESCRIPTION, ICON_NAME, COLOR_PRIMARY, COLOR_SECONDARY, ESTIMATED_TIME_MINUTES, REQUIRES_DOCUMENTATION, DISPLAY_ORDER) VALUES
    ('RECLAMOS_PQR', 'Reclamos PQR', 'Atención de peticiones, quejas y reclamos', 'clipboard-list', '#14B8A6', '#2DD4BF', 30, 0, 7);
INSERT INTO ADMIN.AppointmentTypes (CODE, NAME, DESCRIPTION, ICON_NAME, COLOR_PRIMARY, COLOR_SECONDARY, ESTIMATED_TIME_MINUTES, REQUIRES_DOCUMENTATION, DISPLAY_ORDER) VALUES
    ('CUENTA_NUEVA', 'Cuenta Nueva', 'Solicitud de apertura de cuenta nueva', 'user-plus', '#7C3AED', '#A78BFA', 30, 1, 8);
INSERT INTO ADMIN.AppointmentTypes (CODE, NAME, DESCRIPTION, ICON_NAME, COLOR_PRIMARY, COLOR_SECONDARY, ESTIMATED_TIME_MINUTES, REQUIRES_DOCUMENTATION, DISPLAY_ORDER) VALUES
    ('PROYECTO_NUEVO', 'Proyecto Nuevo', 'Solicitud de proyecto eléctrico nuevo', 'project-diagram', '#DC2626', '#F87171', 45, 1, 9);

-- CLIENTS (DOCUMENT_TYPE es NUMBER: 1=CC, 2=TI, 3=RC, 4=CE)
INSERT INTO ADMIN.Clients (CLIENT_NUMBER, DOCUMENT_TYPE, DOCUMENT_NUMBER, FULL_NAME, EMAIL, PHONE, MOBILE, ADDRESS) VALUES
    ('100001', 1, '12345678', 'Juan Carlos Pérez Rodríguez', 'juan.perez@gmail.com', '6088664700', '3154987623', 'Cra 1A #60-79');
INSERT INTO ADMIN.Clients (CLIENT_NUMBER, DOCUMENT_TYPE, DOCUMENT_NUMBER, FULL_NAME, EMAIL, PHONE, MOBILE, ADDRESS) VALUES
    ('100002', 1, '87654321', 'María Elena García López', 'maria.garcia@hotmail.com', '6088664701', '3201234567', 'Calle 15 #45-12');
INSERT INTO ADMIN.Clients (CLIENT_NUMBER, DOCUMENT_TYPE, DOCUMENT_NUMBER, FULL_NAME, EMAIL, PHONE, MOBILE, ADDRESS) VALUES
    ('100003', 1, '900123456', 'Empresa XYZ S.A.S.', 'contacto@xyz.com', '6088664702', '3209876543', 'Av. 15 #45-10');
INSERT INTO ADMIN.Clients (CLIENT_NUMBER, DOCUMENT_TYPE, DOCUMENT_NUMBER, FULL_NAME, EMAIL, PHONE, MOBILE, ADDRESS) VALUES
    ('100004', 1, '23456789', 'Carlos Alberto Martínez Sánchez', 'carlos.martinez@yahoo.com', '6088664703', '3156789012', 'Carrera 5 #25-30');
INSERT INTO ADMIN.Clients (CLIENT_NUMBER, DOCUMENT_TYPE, DOCUMENT_NUMBER, FULL_NAME, EMAIL, PHONE, MOBILE, ADDRESS) VALUES
    ('100005', 1, '34567890', 'Ana Lucía Torres Vargas', 'ana.torres@outlook.com', '6088664704', '3187654321', 'Calle 8 #12-45');
INSERT INTO ADMIN.Clients (CLIENT_NUMBER, DOCUMENT_TYPE, DOCUMENT_NUMBER, FULL_NAME, EMAIL, PHONE, MOBILE, ADDRESS) VALUES
    ('100006', 1, '45678901', 'Roberto José Gómez Herrera', 'roberto.gomez@gmail.com', '6088664705', '3145678901', 'Carrera 12 #8-25');
INSERT INTO ADMIN.Clients (CLIENT_NUMBER, DOCUMENT_TYPE, DOCUMENT_NUMBER, FULL_NAME, EMAIL, PHONE, MOBILE, ADDRESS) VALUES
    ('100007', 1, '56789012', 'Laura Patricia Castillo Mora', 'laura.castillo@hotmail.com', '6088664706', '3176543210', 'Calle 20 #15-60');
INSERT INTO ADMIN.Clients (CLIENT_NUMBER, DOCUMENT_TYPE, DOCUMENT_NUMBER, FULL_NAME, EMAIL, PHONE, MOBILE, ADDRESS) VALUES
    ('100008', 2, '1075287436', 'Diego Fernando Rojas Silva', 'diego.rojas@gmail.com', '6088664707', '3198765432', 'Carrera 7 #30-15');

PROMPT ⏰ Insertando Horarios Disponibles...

-- AVAILABLE TIMES (Business hours for each branch)
-- Sede Principal Neiva
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('08:00', 1, 3);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('08:30', 1, 3);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('09:00', 1, 3);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('09:30', 1, 3);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('10:00', 1, 3);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('10:30', 1, 3);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('11:00', 1, 3);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('11:30', 1, 3);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('14:00', 1, 3);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('14:30', 1, 3);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('15:00', 1, 3);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('15:30', 1, 3);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('16:00', 1, 3);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('16:30', 1, 3);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('17:00', 1, 3);

-- Sede Norte Neiva
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('08:00', 2, 2);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('08:30', 2, 2);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('09:00', 2, 2);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('09:30', 2, 2);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('10:00', 2, 2);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('10:30', 2, 2);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('11:00', 2, 2);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('11:30', 2, 2);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('14:00', 2, 2);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('14:30', 2, 2);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('15:00', 2, 2);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('15:30', 2, 2);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('16:00', 2, 2);

-- Sedes regionales (tiempo limitado)
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('08:00', 3, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('09:00', 3, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('10:00', 3, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('11:00', 3, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('14:00', 3, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('15:00', 3, 1);

INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('08:00', 4, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('09:00', 4, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('10:00', 4, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('11:00', 4, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('14:00', 4, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('15:00', 4, 1);

INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('08:00', 5, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('09:00', 5, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('10:00', 5, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('11:00', 5, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('14:00', 5, 1);
INSERT INTO ADMIN.AvailableTimes (TIME, BRANCH_ID, MAX_APPOINTMENTS_PER_SLOT) VALUES ('15:00', 5, 1);

PROMPT 📅 Insertando Citas de Ejemplo...

-- SAMPLE APPOINTMENTS
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251001-001', SYSDATE + 1, '09:00', 1, 'Cliente solicita conexión nueva para vivienda', 1, 1, 1, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251001-002', SYSDATE + 1, '10:30', 1, 'Reconexión por pago de factura', 2, 1, 2, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251002-003', SYSDATE + 2, '08:30', 2, 'Cambio de medidor por daño', 3, 2, 3, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251002-004', SYSDATE + 2, '14:00', 1, 'Revisión técnica por sobrecarga', 4, 1, 4, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251003-005', SYSDATE + 3, '09:00', 4, 'Consulta sobre facturación', 5, 3, 6, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, COMPLETED_DATE, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20250930-001', SYSDATE - 1, '10:00', 4, 'Instalación completada exitosamente', SYSDATE - 1, 6, 1, 1, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, COMPLETED_DATE, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20250929-001', SYSDATE - 2, '15:00', 4, 'Reclamo resuelto satisfactoriamente', SYSDATE - 2, 7, 2, 7, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CANCELLATION_REASON, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251004-006', SYSDATE + 4, '11:00', 5, 'Cliente canceló por cambio de planes', 'Cambio en cronograma personal', 8, 1, 5, 1);

-- Additional appointments for testing user assignments
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251117-007', SYSDATE, '08:30', 1, 'Nueva cuenta para vivienda familiar', 1, 1, 8, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251117-008', SYSDATE, '09:30', 2, 'Reclamo por cobro excesivo', 2, 1, 7, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251117-009', SYSDATE, '10:00', 1, 'Solicitud de conexión nueva para local comercial', 3, 2, 1, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251117-010', SYSDATE, '11:00', 1, 'Reconexión después de pago', 4, 1, 2, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251117-011', SYSDATE, '14:30', 1, 'PQR sobre cortes frecuentes', 5, 3, 7, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251118-012', SYSDATE + 1, '08:00', 1, 'Proyecto nuevo de edificio', 6, 1, 9, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251118-013', SYSDATE + 1, '09:00', 1, 'Cambio de medidor análogo a digital', 7, 2, 3, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251118-014', SYSDATE + 1, '10:30', 2, 'Revisión técnica de instalación trifásica', 8, 1, 4, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251118-015', SYSDATE + 1, '14:00', 1, 'Cuenta nueva para empresa', 1, 1, 8, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251119-016', SYSDATE + 2, '08:30', 1, 'Consulta sobre tarifas', 2, 3, 6, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251119-017', SYSDATE + 2, '09:30', 1, 'Traslado de medidor a bodega', 3, 2, 5, 1);
INSERT INTO ADMIN.Appointments (APPOINTMENT_NUMBER, APPOINTMENT_DATE, APPOINTMENT_TIME, STATUS_ID, NOTES, CLIENT_ID, BRANCH_ID, APPOINTMENT_TYPE_ID, IS_ENABLED) VALUES
    ('APPT-20251119-018', SYSDATE + 2, '11:00', 3, 'Reconexión programada (no se presentó)', 4, 1, 2, 1);

PROMPT 👥 Insertando Asignaciones de Empleados a Tipos de Cita...

-- USER APPOINTMENT TYPE ASSIGNMENTS
-- Admin (ID=1) gets access to ALL appointment types
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (1, 1, 1); -- CONEXION_NUEVA
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (1, 2, 1); -- RECONEXION
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (1, 3, 1); -- CAMBIO_MEDIDOR
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (1, 4, 1); -- REVISION_TECNICA
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (1, 5, 1); -- TRASLADO_MEDIDOR
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (1, 6, 1); -- CONSULTA_GENERAL
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (1, 7, 1); -- RECLAMOS_PQR
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (1, 8, 1); -- CUENTA_NUEVA
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (1, 9, 1); -- PROYECTO_NUEVO

-- Operator1 (ID=2) handles: CUENTA_NUEVA, RECONEXION
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (2, 8, 1); -- CUENTA_NUEVA
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (2, 2, 1); -- RECONEXION

-- Reception (ID=3) handles: CONSULTA_GENERAL, CUENTA_NUEVA
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (3, 6, 1); -- CONSULTA_GENERAL
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (3, 8, 1); -- CUENTA_NUEVA

-- Tech1 (ID=4) handles: CONEXION_NUEVA, CAMBIO_MEDIDOR, REVISION_TECNICA, TRASLADO_MEDIDOR
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (4, 1, 1); -- CONEXION_NUEVA
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (4, 3, 1); -- CAMBIO_MEDIDOR
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (4, 4, 1); -- REVISION_TECNICA
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (4, 5, 1); -- TRASLADO_MEDIDOR

-- Supervisor (ID=5) handles: RECLAMOS_PQR, PROYECTO_NUEVO
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (5, 7, 1); -- RECLAMOS_PQR
INSERT INTO ADMIN.UserAppointmentTypeAssignments (USER_ID, APPOINTMENT_TYPE_ID, ASSIGNED_BY_USER_ID) VALUES (5, 9, 1); -- PROYECTO_NUEVO

COMMIT;

-- ===================== RESET SEQUENCES AFTER DATA INSERT =====================
PROMPT 🔄 Reseteando Secuencias...
DECLARE
    v_max_id NUMBER;
    v_next_val NUMBER;
BEGIN
    -- AppointmentStatuses
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.AppointmentStatuses;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_APPOINTMENT_STATUSES RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_APPOINTMENT_STATUSES reset to start with ' || v_max_id);

    -- ProjectTypes
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.ProjectTypes;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_PROJECT_TYPES RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_PROJECT_TYPES reset to start with ' || v_max_id);

    -- PropertyTypes
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.PropertyTypes;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_PROPERTY_TYPES RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_PROPERTY_TYPES reset to start with ' || v_max_id);

    -- ServiceUseTypes
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.ServiceUseTypes;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_SERVICE_USE_TYPES RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_SERVICE_USE_TYPES reset to start with ' || v_max_id);

    -- ThemeSettings
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.ThemeSettings;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_THEME_SETTINGS RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_THEME_SETTINGS reset to start with ' || v_max_id);

    -- SystemSettings
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.SystemSettings;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_SYSTEM_SETTINGS RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_SYSTEM_SETTINGS reset to start with ' || v_max_id);

    -- Modules
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.Modules;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_MODULES RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_MODULES reset to start with ' || v_max_id);

    -- Forms
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.Forms;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_FORMS RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_FORMS reset to start with ' || v_max_id);

    -- FormModules
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.FormModules;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_FORM_MODULES RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_FORM_MODULES reset to start with ' || v_max_id);

    -- Permissions
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.Permissions;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_PERMISSIONS RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_PERMISSIONS reset to start with ' || v_max_id);

    -- Roles
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.Roles;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_ROLES RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_ROLES reset to start with ' || v_max_id);

    -- Users
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.Users;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_USERS RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_USERS reset to start with ' || v_max_id);

    -- RolUsers
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.RolUsers;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_ROL_USERS RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_ROL_USERS reset to start with ' || v_max_id);

    -- RolFormPermis
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.RolFormPermis;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_ROL_FORM_PERMIS RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_ROL_FORM_PERMIS reset to start with ' || v_max_id);

    -- Branches
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.Branches;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_BRANCHES RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_BRANCHES reset to start with ' || v_max_id);

    -- Clients
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.Clients;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_CLIENTS RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_CLIENTS reset to start with ' || v_max_id);

    -- Holidays
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.Holidays;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_HOLIDAYS RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_HOLIDAYS reset to start with ' || v_max_id);

    -- AppointmentTypes
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.AppointmentTypes;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_APPOINTMENT_TYPES RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_APPOINTMENT_TYPES reset to start with ' || v_max_id);

    -- Appointments
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.Appointments;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_APPOINTMENTS RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_APPOINTMENTS reset to start with ' || v_max_id);

    -- AvailableTimes
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.AvailableTimes;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_AVAILABLE_TIMES RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_AVAILABLE_TIMES reset to start with ' || v_max_id);

    -- AppointmentDocuments (usually empty)
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.AppointmentDocuments;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_APPOINTMENT_DOCUMENTS RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_APPOINTMENT_DOCUMENTS reset to start with ' || v_max_id);

    -- Notifications (usually empty)
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.Notifications;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_NOTIFICATIONS RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_NOTIFICATIONS reset to start with ' || v_max_id);

    -- UserAppointmentTypeAssignments
    SELECT NVL(MAX(ID), 0) + 1 INTO v_max_id FROM ADMIN.UserAppointmentTypeAssignments;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE ADMIN.SEQ_USER_APPT_TYPE_ASSIGNS RESTART START WITH ' || v_max_id;
    DBMS_OUTPUT.PUT_LINE('SEQ_USER_APPT_TYPE_ASSIGNS reset to start with ' || v_max_id);
END;
/

-- ===================== CREATE PERFORMANCE INDEXES =====================

PROMPT 🚀 Creando Índices de Performance...

-- Appointments indexes
CREATE INDEX IDX_APPOINTMENTS_DATE ON ADMIN.Appointments(APPOINTMENT_DATE);
CREATE INDEX IDX_APPOINTMENTS_STATUS ON ADMIN.Appointments(STATUS_ID);
CREATE INDEX IDX_APPOINTMENTS_CLIENT ON ADMIN.Appointments(CLIENT_ID);
CREATE INDEX IDX_APPOINTMENTS_BRANCH ON ADMIN.Appointments(BRANCH_ID);
CREATE INDEX IDX_APPOINTMENTS_TYPE ON ADMIN.Appointments(APPOINTMENT_TYPE_ID);

-- Clients indexes
CREATE INDEX IDX_CLIENTS_DOCUMENT ON ADMIN.Clients(DOCUMENT_TYPE, DOCUMENT_NUMBER);
-- EMAIL already indexed (UNIQUE constraint)
CREATE INDEX IDX_CLIENTS_FULL_NAME ON ADMIN.Clients(FULL_NAME);

-- Users indexes
-- EMAIL and USERNAME already indexed (UNIQUE constraints)

-- AvailableTimes indexes
CREATE INDEX IDX_AVAILABLETIMES_BRANCH ON ADMIN.AvailableTimes(BRANCH_ID);
CREATE INDEX IDX_AVAILABLETIMES_TYPE ON ADMIN.AvailableTimes(APPOINTMENT_TYPE_ID);

-- Holidays indexes
CREATE INDEX IDX_HOLIDAYS_DATE ON ADMIN.Holidays(HOLIDAY_DATE);
CREATE INDEX IDX_HOLIDAYS_BRANCH ON ADMIN.Holidays(BRANCH_ID);

-- AppointmentDocuments indexes
CREATE INDEX IDX_APPTDOCS_APPOINTMENT ON ADMIN.AppointmentDocuments(APPOINTMENT_ID);

-- Notifications indexes
CREATE INDEX IDX_NOTIFICATIONS_USER_ID ON ADMIN.Notifications(USER_ID);
CREATE INDEX IDX_NOTIFICATIONS_CLIENT_ID ON ADMIN.Notifications(CLIENT_ID);
CREATE INDEX IDX_NOTIFICATIONS_APPOINTMENT_ID ON ADMIN.Notifications(APPOINTMENT_ID);
CREATE INDEX IDX_NOTIFICATIONS_STATUS ON ADMIN.Notifications(STATUS);
CREATE INDEX IDX_NOTIFICATIONS_USER_ISREAD ON ADMIN.Notifications(USER_ID, IS_READ);
CREATE INDEX IDX_NOTIFICATIONS_CLIENT_CREATED ON ADMIN.Notifications(CLIENT_ID, CREATED_AT);
CREATE INDEX IDX_NOTIFICATIONS_SENT_AT ON ADMIN.Notifications(SENT_AT);
CREATE INDEX IDX_NOTIFICATIONS_USER_CREATED ON ADMIN.Notifications(USER_ID, CREATED_AT);

-- System indexes
-- SETTING_KEY already indexed (UNIQUE constraint)

-- ===================== ADD TABLE COMMENTS =====================

PROMPT 📝 Agregando Comentarios a Tablas...

-- Business tables
COMMENT ON TABLE ADMIN.Appointments IS 'Tabla de citas programadas por clientes para servicios de ElectroHuila';
COMMENT ON TABLE ADMIN.Clients IS 'Tabla de clientes registrados en el sistema';
COMMENT ON TABLE ADMIN.Branches IS 'Sucursales y puntos de atención de ElectroHuila';
COMMENT ON TABLE ADMIN.AppointmentTypes IS 'Catálogo de tipos de cita disponibles (conexión, reconexión, etc.)';
COMMENT ON TABLE ADMIN.AppointmentStatuses IS 'Estados posibles de una cita (pendiente, confirmada, completada, etc.)';
COMMENT ON TABLE ADMIN.AvailableTimes IS 'Horarios disponibles para agendamiento de citas por sucursal';
COMMENT ON TABLE ADMIN.AppointmentDocuments IS 'Documentos adjuntos relacionados con citas';
COMMENT ON TABLE ADMIN.UserAppointmentTypeAssignments IS 'Asignaciones de empleados (usuarios) a tipos de cita específicos para filtrado automático en "Mis Citas"';
COMMENT ON COLUMN ADMIN.UserAppointmentTypeAssignments.USER_ID IS 'ID del usuario/empleado asignado';
COMMENT ON COLUMN ADMIN.UserAppointmentTypeAssignments.APPOINTMENT_TYPE_ID IS 'ID del tipo de cita asignado';
COMMENT ON COLUMN ADMIN.UserAppointmentTypeAssignments.ASSIGNED_BY_USER_ID IS 'ID del administrador que realizó la asignación';
COMMENT ON COLUMN ADMIN.UserAppointmentTypeAssignments.ASSIGNED_AT IS 'Fecha y hora de la asignación';

-- Configuration tables
COMMENT ON TABLE ADMIN.ThemeSettings IS 'Configuración de temas visuales de la aplicación';
COMMENT ON TABLE ADMIN.SystemSettings IS 'Configuración general del sistema en runtime';
COMMENT ON TABLE ADMIN.Notifications IS 'Registro de notificaciones enviadas a usuarios (Email, SMS, WhatsApp, IN_APP)';
COMMENT ON TABLE ADMIN.Holidays IS 'Festivos y días no laborables para evitar agendamiento';

-- Notifications table columns
COMMENT ON COLUMN ADMIN.Notifications.USER_ID IS 'ID del usuario admin destinatario (NULL si es para cliente). Solo para notificaciones IN_APP';
COMMENT ON COLUMN ADMIN.Notifications.CLIENT_ID IS 'ID del cliente destinatario (NULL si es para usuario). Para notificaciones EMAIL/WHATSAPP';
COMMENT ON COLUMN ADMIN.Notifications.APPOINTMENT_ID IS 'ID de la cita relacionada (opcional)';
COMMENT ON COLUMN ADMIN.Notifications.TYPE IS 'Tipo de notificación: EMAIL, WHATSAPP, IN_APP';
COMMENT ON COLUMN ADMIN.Notifications.STATUS IS 'Estado del envío: PENDING, SENT, FAILED';
COMMENT ON COLUMN ADMIN.Notifications.SENT_AT IS 'Fecha y hora de envío exitoso';
COMMENT ON COLUMN ADMIN.Notifications.READ_AT IS 'Fecha y hora de lectura (solo IN_APP)';
COMMENT ON COLUMN ADMIN.Notifications.IS_READ IS 'Indica si fue leída (solo IN_APP)';
COMMENT ON COLUMN ADMIN.Notifications.ERROR_MESSAGE IS 'Mensaje de error en caso de fallo';
COMMENT ON COLUMN ADMIN.Notifications.METADATA IS 'Datos adicionales en formato JSON';

-- Catalog tables
COMMENT ON TABLE ADMIN.ProjectTypes IS 'Catálogo de tipos de proyecto eléctrico';
COMMENT ON TABLE ADMIN.PropertyTypes IS 'Catálogo de tipos de propiedad';
COMMENT ON TABLE ADMIN.ServiceUseTypes IS 'Catálogo de tipos de uso del servicio eléctrico';

-- Security tables
COMMENT ON TABLE ADMIN.Users IS 'Usuarios del sistema con acceso al panel administrativo';
COMMENT ON TABLE ADMIN.Roles IS 'Roles de seguridad del sistema';
COMMENT ON TABLE ADMIN.Permissions IS 'Permisos CRUD (crear, leer, actualizar, eliminar)';
COMMENT ON TABLE ADMIN.Forms IS 'Formularios/pantallas de la aplicación';
COMMENT ON TABLE ADMIN.Modules IS 'Módulos funcionales del sistema';
COMMENT ON TABLE ADMIN.RolUsers IS 'Relación muchos a muchos entre roles y usuarios';
COMMENT ON TABLE ADMIN.FormModules IS 'Relación muchos a muchos entre formularios y módulos';
COMMENT ON TABLE ADMIN.RolFormPermis IS 'Permisos específicos de roles sobre formularios';

PROMPT ===============================================
PROMPT    ✅ RESET COMPLETADO EXITOSAMENTE!
PROMPT ===============================================
PROMPT 📊 Estadísticas de la Base de Datos:
PROMPT
PROMPT 📋 TABLAS DE CATÁLOGO:
PROMPT    • 6 Estados de Citas con colores e iconos
PROMPT    • 5 Tipos de Proyecto con iconos y colores
PROMPT    • 5 Tipos de Propiedad
PROMPT    • 4 Tipos de Uso de Servicio
PROMPT
PROMPT ⚙️  CONFIGURACIÓN:
PROMPT    • 1 Tema ElectroHuila (con descripción y flag default)
PROMPT    • 8 Configuraciones del Sistema
PROMPT    • 4 Plantillas de Notificación (Email y SMS)
PROMPT    • 0 Notificaciones iniciales (tabla vacía)
PROMPT    • 18 Festivos Colombianos 2025
PROMPT
PROMPT 🏢 DATOS DE NEGOCIO:
PROMPT    • 5 Sucursales con colores corporativos
PROMPT    • 9 Tipos de Cita con estimación de tiempo
PROMPT    • 8 Clientes de Prueba (con DocumentType enum)
PROMPT    • 53 Horarios Disponibles distribuidos
PROMPT    • 20 Citas de Ejemplo (varios estados y tipos)
PROMPT    • 29 Asignaciones de Empleados a Tipos de Cita
PROMPT
PROMPT 🔐 SEGURIDAD Y PERMISOS:
PROMPT    • 9 Formularios del sistema
PROMPT    • 5 Módulos funcionales
PROMPT    • 5 Roles de Usuario con permisos
PROMPT    • 5 Usuarios (contraseña: Admin123!)
PROMPT    • 5 Tipos de Permisos CRUD
PROMPT
PROMPT 🚀 PERFORMANCE:
PROMPT    • 27 Índices de performance creados
PROMPT    • Comentarios agregados a todas las tablas
PROMPT
PROMPT ===============================================
PROMPT ✨ AJUSTES CLAVE (V4.1 - SISTEMA DE NOTIFICACIONES):
PROMPT    ✅ DocumentType ahora es ENUM en código (no tabla)
PROMPT    ✅ Clients.DOCUMENT_TYPE es NUMBER (1=CC, 2=TI, 3=RC, 4=CE)
PROMPT    ✅ Eliminadas tablas obsoletas: DocumentTypes, NewAccounts, ProjectNews, NewAccountStatuses
PROMPT    ✅ Sistema unificado de citas (Appointments) para todos los flujos
PROMPT    ✅ ThemeSettings con DESCRIPTION e IS_DEFAULT_THEME
PROMPT    ✅ Nuevas tablas: SystemSettings, Notifications, Holidays, AppointmentDocuments, UserAppointmentTypeAssignments
PROMPT    ✅ Sistema de notificaciones completo (Email, SMS, WhatsApp, IN_APP)
PROMPT    ✅ Registro de todas las notificaciones enviadas en tabla Notifications
PROMPT    ✅ Índices optimizados para queries de notificaciones no leídas
PROMPT    ✅ Índices de performance en tablas principales (27 total)
PROMPT    ✅ Comentarios de documentación en todas las tablas
PROMPT    ✅ 18 festivos colombianos 2025 pre-cargados
PROMPT    ✅ Sistema de asignación de empleados a tipos de cita
PROMPT    ✅ Todas las tablas coinciden con EntityTypeConfiguration
PROMPT ===============================================
PROMPT 🎯 TOTAL: 23 TABLAS OPERATIVAS
PROMPT ===============================================
PROMPT 🚀 ¡Base de datos lista para PRODUCCIÓN con .NET!
PROMPT ===============================================

-- Mostrar resumen completo
SELECT 'AppointmentStatuses' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.AppointmentStatuses
UNION ALL SELECT 'ProjectTypes' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.ProjectTypes
UNION ALL SELECT 'PropertyTypes' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.PropertyTypes
UNION ALL SELECT 'ServiceUseTypes' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.ServiceUseTypes
UNION ALL SELECT 'ThemeSettings' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.ThemeSettings
UNION ALL SELECT 'SystemSettings' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.SystemSettings
UNION ALL SELECT 'Notifications' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.Notifications
UNION ALL SELECT 'Holidays' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.Holidays
UNION ALL SELECT 'Branches' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.Branches
UNION ALL SELECT 'AppointmentTypes' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.AppointmentTypes
UNION ALL SELECT 'Clients' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.Clients
UNION ALL SELECT 'AvailableTimes' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.AvailableTimes
UNION ALL SELECT 'Appointments' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.Appointments
UNION ALL SELECT 'AppointmentDocuments' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.AppointmentDocuments
UNION ALL SELECT 'Users' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.Users
UNION ALL SELECT 'Roles' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.Roles
UNION ALL SELECT 'Forms' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.Forms
UNION ALL SELECT 'Modules' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.Modules
UNION ALL SELECT 'Permissions' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.Permissions
UNION ALL SELECT 'RolUsers' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.RolUsers
UNION ALL SELECT 'FormModules' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.FormModules
UNION ALL SELECT 'RolFormPermis' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.RolFormPermis
UNION ALL SELECT 'UserAppointmentTypeAssignments' AS TABLE_NAME, COUNT(*) AS RECORDS FROM ADMIN.UserAppointmentTypeAssignments
ORDER BY TABLE_NAME;
